### ISSUE TITLE
쓰레드 생성시 이모지(😊) DB에 바로 안들어가지는 문제

### ISSUE THREAD

**Issue by grap3fruit** [boostcamp-2020/Project06-A-Slack#57]
![image](https://user-images.githubusercontent.com/13213473/100877815-a92a9b00-34ec-11eb-85ac-10eb202b7cd9.png)

위와 같은 에러 뜨면서 그대로 안들어가짐

추후 보완..

**Comment by rnjshippo** [comment]
저번 이슈트래커 할 때 이렇게 바꾸니깐 이모지가 들어갔습니다 🙂

![image](https://user-images.githubusercontent.com/61396464/100888756-ca45b880-34f9-11eb-88aa-20625e7ffece.png)
