### ISSUE TITLE
Firefox에서 SVG 에 rem 크기 적용시 이슈

### ISSUE THREAD

**Issue by grap3fruit** [boostcamp-2020/Project06-A-Slack#82]
![image](https://user-images.githubusercontent.com/13213473/101355377-d35bce80-38d9-11eb-8710-7f9978a92899.png)

Firefox에서 SVG 태그에 rem 크기를 인라인으로 적용시 위와같은 경고가 콘솔에 찍히며,,
SVG에 인라인으로 width와 height를 넣지 않고 CSS로 적용하면 가능하다는 얘기가 있습니다.
추후 보완이 필요할듯 합니당😂

참고 : https://bugzilla.mozilla.org/show_bug.cgi?id=1231147

**Comment by rnjshippo** [comment]
해결!
